import 'score_category_breakdown.dart';

/// Complete explainable score result generated by Score Engine V2.
class DailyScoreExplanation {
  final DateTime date;
  final int finalScore; // 0 to 100
  final double baseScore;
  final double progressMultiplier; // 1.0 to 1.1x
  final double emaBaseline7d;
  final Map<String, ScoreCategoryBreakdown> categories;
  final String scoreVersion;

  const DailyScoreExplanation({
    required this.date,
    required this.finalScore,
    required this.baseScore,
    required this.progressMultiplier,
    required this.emaBaseline7d,
    required this.categories,
    required this.scoreVersion,
  });
}
